### ISSUE TITLE
Data must be a string or a buffer

### ISSUE THREAD

**Issue by Gigiz** [flamelink/gatsby-source-flamelink#11]
Hi, I am new to Flamelink and Gatsby. I am trying to build up a simple demo project.
But I have got this error

```
 source and transform nodes
  flamelink:info Starting with config: {"plugins":[],"firebaseConfig":{"privateKey":"-----BEGIN PRIVATE KEY----- ******   -----END PRIVATE KEY-----\n",
"databaseURL":"https://******.firebaseio.com","storageBucket":"*****.appspot.com","projectId":"*******","clientEmail":"firebase-adminsdk-g09pt@*******.iam.gserviceaccount.com"},
"environment":"production",
"content":true,
"populate":true,
"navigation":true,
"globals":true,
"dbType":"cf"
} +0ms
⠏ source and transform nodes
  flamelink:error TypeError: Data must be a string or a buffer
  flamelink:error     at Hash.update (crypto.js:99:16)
  flamelink:error     at digest (/home/developer/Workspace/gigiz/happy-journey/node_modules/gatsby-source-flamelink/helpers/normalize.js:47:48)
  flamelink:error     at Object.processGlobals (/home/developer/Workspace/gigiz/happy-journey/node_modules/gatsby-source-flamelink/helpers/normalize.js:372:22)
  flamelink:error     at Object.<anonymous> (/home/developer/Workspace/gigiz/happy-journey/node_modules/gatsby-source-flamelink/gatsby-node.js:80:30)
  flamelink:error     at Generator.next (<anonymous>)
  flamelink:error     at asyncGeneratorStep (/home/developer/Workspace/gigiz/happy-journey/node_modules/gatsby-source-flamelink/gatsby-node.js:3:103)
  flamelink:error     at _next (/home/developer/Workspace/gigiz/happy-journey/node_modules/gatsby-source-flamelink/gatsby-node.js:5:194)
  flamelink:error     at <anonymous>
```

I created one Schema and I can see data into Firebase Cloud Firestore.

**Comment by Gigiz** [comment]
Today I'm trying with Realtime Database and it works like a charm.
So Cloud Firestore is the problem.

**Comment by jperasmus** [comment]
Hi @Gigiz thanks for creating this issue. Can you try and comment out the `navigation`, `globals` and `content` config options individually to see if the error is specific to one of them?

Can you also give me an example of the schemas that you have set up in CF when the error happens?

**Comment by jperasmus** [comment]
Hi @Gigiz I checked this now and can confirm that I get the same error for Cloud Firestore if I have the `globals: true` config setting enabled and I don't have global content set up in the CMS.

You can disable that in the meantime, but I'll look into why this is happening as soon as I get some time this week.

**Comment by caweidmann** [comment]
This is on the latest release, `v3.0.0`.
